# Build properties used by zAppBuild/build.groovy

# Run zUnit Tests
# Defaults to "false", to enable, set to "true"
runzTests=true

##
# Comma separated list of additional application property files to load
# Supports both relative path (to ${application}/application-conf/) and absolute path
#applicationPropFiles=file.properties,Assembler.properties,BMS.properties,Cobol.properties,\
#LinkEdit.properties,languageConfigurationMapping.properties,\
#CRB.properties,Easytrieve.properties,TazUnitTest.properties

applicationPropFiles=file.properties,cics_list.properties,bind.properties,Assembler.properties,\
BMS.properties,Cobol.properties,LinkEdit.properties,bind.properties,\
REXX.properties,TazUnitTest.properties,\
Transfer.properties,CRB.properties,Easytrieve.properties,\
reports.properties,languageConfigurationMapping.properties

#
# Comma separated list all source directories included in application build. Supports both absolute
# and relative paths.  Relative assumed to be relative to ${workspace}.
# ex: applicationSrcDirs=${application},/u/build/common/copybooks
applicationSrcDirs=${application}

#
# Comma separated list all source PEM directories included in application build. Supports both absolute
# and relative paths.  Relative assumed to be relative to ${workspace}.
# ex: applicationSrcDirs=${application},/u/build/common/copybooks
pemSrcDirs=${application}/assembler/src


#
# Comma separated list of the build script processing order
# Comment: We do not expect zAppBuild users to use the CICS Resource Builder yet,
#  and have therefore deactivated processing the Resource Builder files.

#
# Comma separated list of the build script processing order
#buildOrder=BMS.groovy,MFS.groovy,Cobol.groovy,Assembler.groovy,PLI.groovy,\
#LinkEdit.groovy,DBDgen.groovy,PSBgen.groovy,Transfer.groovy,CRB.groovy,zCEE2.groovy
buildOrder=BMS.groovy,BMSUtil.groovy,Cobol.groovy,Assembler.groovy,AsmUtil.groovy,Easytrieve.groovy,LinkEdit.groovy

#
# Comma seperated list of the test script processing order
testOrder=TazUnitTest.groovy

#
# Flag to log output in table views instead of printing raw JSON data
# See also build-conf/build.properties
# default = false
# formatConsoleOutput=false
formatConsoleOutput=true

#
# The main build branch.  Used for cloning collections for topic branch builds instead
# of rescanning the entire application.
mainBuildBranch=dev

#
# The git repository URL of the application repository to establish links to the changed files
# in the build result properties
# ex: GitHub: https://github.com/ibm/dbb-zappbuild/
gitRepositoryURL=https://gitlab.com/mandtbank/mtb/mainframedev/hogan/iba/

#
# exclude list used when scanning or running full build
#### Pipeline development settings for use when developing pipeline.  some directories have been excluded if certain build types are not ready.

excludeFileList=.*, \
                 **/.*, \
                 **/*.ctl, \
                 **/*.dat, \
                 **/*.groovy, \
                 **/*.md, \
                 **/*.jcl, \
                 **/*.json, \
                 **/*.properties, \
                 **/*.py, \
                 **/*.sh, \
                 **/*.txt, \
                 **/*.xml, \
                 **/*.yaml, \
                 **/*.yml, \
                 **/application-conf/**, \
                 **/build/**, \
                 **/ci-cd/**, \
                 **/ctl/**, \
                 **/docutext/**, \
                 **/hold/**, \
                 **/job/**, \
                 **/other/**, \
                 **/procs/**, \
                 **/properties/**, \
                 **/unknown/**, \
                 **/pipeline-properties/**, \
                 **/.settings/**, \
                 **/bms/src/p49840mm.bms, \
                 **/bms/src/p49841mm.bms, \
                 **/bms/src/p49842mm.bms, \
                 **/bms/src/x48110mm.bms, \
                 /*

#
# comma-separated list of file patterns for which impact calculation should be skipped. Uses glob file patterns
# sample: skipImpactCalculationList=**/epsmtout.cpy,**/centralCopybooks/*.cpy
skipImpactCalculationList=**/p49000d.cpy

#
# Job card, please use \n to indicate a line break and use \ to break the line in this property file
# Example: jobCard=//RUNZUNIT JOB ,MSGCLASS=H,CLASS=A,NOTIFY=&SYSUID,REGION=0M
jobCard=

###############################################################
# Build Property management
###############################################################
# zAppBuild allows you to manage default properties and file properties:
# - Documentation on how to override corresponding default build properties can be found at:
#   https://github.com/IBM/dbb-zappbuild/docs/FilePropertyManagement.md

# ### Properties to enable and configure build property overrides using individual artifact properties files

# flag to enable the zAppBuild capability to load individual artifact properties files for all individual source files.
# Note: To only activate loadFileLevelProperties for a group of files, it is recommended to use DBB's file property path
# syntax in application-conf/file.properties instead.
# default: false
loadFileLevelProperties=true

# Property to enable/disable and configure build property overrides using language configuration mapping
# file - languageConfigurationMapping.properties
# If loadFileLevelProperties is set as true above, the properties from the individual artifact properties files will override the
# properties from language configuration properties file.
# Note: To only activate loadLanguageConfigurationProperties for a group of files, it is recommended to use DBB's file property path
# syntax in application-conf/file.properties instead.
loadLanguageConfigurationProperties=true

# relative path to folder containing individual artifact properties files
# assumed to be relative to ${workspace}/${application}
propertyFilePath=properties

# file extension for individual artifact properties files
# default: properties
propertyFileExtension=properties

###############################################################
# Dependency Analysis and Impact Analysis configuration
###############################################################
#
# boolean flag to configure the SearchPathDependencyResolver to evaluate if resolved dependencies impact
#  the file flags isCICS, isSQL, isDLI, isMQ when creating the LogicalFile
#
#  default:false
#resolveSubsystems=false
resolveSubsystems=true

#
# SearchPathImpactFinder resolution searchPath configuration
#  list of multiple search path configurations which are defined below
#
# this configuration is used when running zAppBuild with the --impactBuild option
#  to calculate impacted files based on the identified changed files

# DEMO Temp change to test impact build for copybook and cobol only
impactSearch=${copybookSearch}${bmsSearch}${linkSearch}${asmMacroSearch}${asmCopySearch}${zunitTestConfigSearch}${zunitTestcasePgmSearch}${eztMacSearch}

#
# copybookSearch
# searchPath to locate Cobol copybooks
# used in dependency resolution and impact analysis
#
# Please be as specific as possible when configuring the searchPath.
# Alternate configurations:
#
# dependency resolution from multiple repositories / multiple root folders:
# copybookSearch = search:${workspace}/?path=**/copybook/*.cpy
#
# dependency resolution across all directories in build workspace, but filtering on the file extension cpy:
# copybookSearch = search:${workspace}/?path=**/*.cpy
# dependency resolution across all directories in build workspace, but filtering on the file extension cpy and cobcpy:
# copybookSearch = search:${workspace}/?path=**/*.cpy;**/*.cobcpy
#
# dependency resolution in the application directory and a shared common copybook location:
# copybookSearch = search:${workspace}/?path=${application}/copybook/*.cpy;/u/build/common/copybooks/*.cpy
#
# More samples can be found at: https://www.ibm.com/docs/en/dbb/2.0.0?topic=apis-dependency-impact-resolution
#
copybookSearch = search:${workspace}/?path=${application}/cobol/copybook/*.cpy

# asmMacroSearch
# searchPath to locate Assembler macro files
# use category filters on what you want to include during the scan (i.e.
# used in dependency resolution and impact analysis
asmMacroSearch = search:[SYSLIB:MACRO]${workspace}/?path=${application}/assembler/macros/*.mac
# asmCopySearch
# searchPath to locate Assembler copy files
# used in dependency resolution and impact analysis
asmCopySearch = search:[SYSLIB:COPY]${workspace}/?path=${application}/assembler/macros/*.mac
#
# bmsSearch
# searchPath to locate impacted bms maps
# used only in impact analysis
bmsSearch = search:${workspace}/?path=${application}/bms/*.bms

#
# rexxCopySearch
# searchPath to locate rexx copy - defaults to the local rexx folder in the main application folder
# used in dependency resolution and impact analysis
rexxCopySearch = search:[SYSLIB:COPY]${workspace}/?path=${application}/rexx/*.rexx

#
# linkSearch
#
# searchPath to locate impacted linkcards or main programs after an included submodule is changed
# leverages the output collection, which has the dependency info from the executable
# category LINK only; used only in impact analysis
#
# Additional samples:
#
# impact resolution across all directories in build workspace, but filtering on the file extension cbl:
# staticLinkSearch = search:[:LINK]${workspace}/?path=**/*.cbl
#
# impact resolution across all directories in build workspace, but filtering on the file extension cbl and pli (for cobol and pli submodules):
# staticLinkSearch = search:[:LINK]${workspace}/?path=**/cobol/src/*.cbl,**/*.pli
#
# Special case with Dependency Scanner Transfer Control Statement capturing turned on (default is off)
# the scanners detect a static call to the literal, which would need to turn into a new rule for CALL:
# staticCallSearch = search:[:CALL]${workspace}/?path=${application}/cobol/*.cbl
#
linkSearch = search:[:LINK]${workspace}/?path=${application}/cobol/src/*.cbl
#
eztMacSearch = search:[SYSLIB:MACRO]${workspace}/?path=${application}/ezt/macros/*.eztm
#eztMacroSearch = search:[MACDD:MACRO]${workspace}/?path=${application}/ezt/macros/*.eztm


# tazTestConfigSearch
# searchPath to locate TAZ test configuration files
# used in impact analysis
tazTestConfigSearch = search:[:ZUNITINC]${workspace}/?path=${application}/cobol/**/*.cbl;${application}/tests/**/*.cbl

#
# tazRecordingFileSearch
# searchPath to locate TAZ recording files
# used in dependency resolution
tazRecordingFileSearch = search:[SYSPLAY:]${workspace}/?path=${application}/tests/**/*.rec

#
# tazTestcasePgmSearch
# searchPath to locate impacted test case programs
# see also build-conf/build.properties -> createTestcaseDependency
# used in impact analysis
tazTestcasePgmSearch = search:[SYSPROG:PROGRAMDEPENDENCY]${workspace}/?path=${application}/cobol/**/*.cbl

