# Application properties used by zAppBuild/language/Assembler.groovy

#
# default Assemble program build rank - used to sort language build file list
# leave empty - overridden by file properties if sorting needed
# example: assembler_fileBuildRank = 1 :: **/assembler/*.asu
assembler_fileBuildRank = 10 :: **/p490*.asu
assembler_fileBuildRank = 20 :: **/p49106.asu,**/p49153.asu
assembler_fileBuildRank = 30 :: **/p495*.asu
assembler_fileBuildRank = 40 :: **/p49870.asu,**/p49871.asu
assembler_fileBuildRank = 50 :: **/p49912.asu
assembler_fileBuildRank = 60 :: **/pem*.asu
assembler_fileBuildRank = 70 :: **/r6*.asu
assembler_fileBuildRank = 71 :: **/u48*.asu,**/u50*.asu,**/u91*.asu
assembler_fileBuildRank = 72 :: **/t50328.asu
assembler_fileBuildRank = 73 :: **/x55*.asu
assembler_fileBuildRank = 100 :: **/p49999.asu


assembler_isPEM=true :: **/p49001.asu,**/p49002.asu,**/p49003.asu,**/p49004.asu,**/p49005.asu,**/p49008.asu,**/p49009.asu,**/p49010.asu,**/p49011.asu,**/p49013.asu,**/p49014.asu,**/p49015.asu,**/p49018.asu,\
**/p49022.asu,**/p49023.asu,**/p49024.asu,**/p49026.asu,**/p49028.asu,**/p49029.asu,**/p49030.asu,**/p49031.asu,**/p49032.asu,**/p49033.asu,**/p49037.asu,**/p49039.asu,\
**/p49042.asu,**/p49043.asu,**/p49048.asu,**/p49052.asu,**/p49053.asu,**/p49054.asu,**/p49055.asu,**/p49057.asu,\
**/p49060.asu,**/p49061.asu,**/p49063.asu,**/p49064.asu,**/p49065.asu,**/p49068.asu,**/p49074.asu,**/p49075.asu,**/p49077.asu,**/p49078.asu,\
**/p49080.asu,**/p49087.asu,**/p49088.asu,**/p49091.asu,**/p49098.asu,**/p49106.asu,**/p49153.asu,**/p49158.asu,\
**/p49501.asu,**/p49519.asu,**/p49528.asu,**/p49543.asu,**/p49599.asu,**/p49902.asu,**/p49999.asu

assembler_isPEMCICS=true :: **/p49046.asu,**/p49051.asu,**/p49502.asu,**/p49870.asu,**/p49871.asu,**/pem2cee.asu,**/pem2cod.asu,**/pemcostd.asu

assembler_isPEMBATCH=true :: **/p49006.asu,**/p49007.asu, **/p49020.asu, **/p49021.asu,**/p49025.asu,**/p49034.asu,**/p49036.asu,\
**/p49038.asu,**/p49040.asu,**/p49041.asu,**/p94045.asu,**/p49047.asu,**/p49049.asu,\
**/p49050.asu,**/p49056.asu,**/p49058.asu,**/p49059.asu,**/p49062.asu,**/p49066.asu,**/p49067.asu,**/p49069.asu,\
**/p49076.asu,**/p49086.asu,**/p49094.asu,**/p49095.asu,**/p49096.asu,**/p49097.asu,**/p49099.asu,**/p49512.asu,**/p49515.asu,**/p49547.asu,\
**/r60031.asu,**/t50328.asu,**/u48733.asu

assembler_isPEMSpecialHandling=true :: **/pem2cee.asu,**/pem2cod.asu,**/pemcostd.asu, \
**/t50328.asu,**/u50572.asu,**/u50574.asu,**/u91019.asu,**/x55076.asu

assembler_CICSPEM=true :: **/p49999.asu
assembler_BATCHPEM=true :: **/p49999.asu

#
# default Assembler parameters
# can be overridden by file properties
assembler_pgmParms=NODECK,OBJECT,TERM,RENT
assembler_pgmParms=NODECK,OBJECT,TERM,SYSPARM(BATCHPEM),RENT :: **/p49644.asm,**/p49646.asm,**/r60090.asm,**/t58020.asm,**/u48739.asm
assembler_pgmParms=NODECK,OBJECT,TERM,SYSPARM(CICSPEM),RENT :: **/x64412.asm,**/x64422.asm

assembler_debugParms=
assembler_compileErrorPrefixParms=ADATA,EX(ADX(ELAXHASM))
assembler_eqalangxParms=(ASM ERROR LOUD
assembler_db2precompilerParms=HOST(ASM)
assembler_cicsprecompilerParms=CICS,NOEPILOG,NOPROLOG,SP,GDS
#assembler_cicsprecompilerParms=
assembler_linkEditParms=LIST,MAP,XREF
assembler_linkEditRent=RENT

assembler_linkEditParms=${assembler_linkEditParms},CALL,AMODE(24),RMODE(24) :: **/A24R24/*.asm
assembler_linkEditParms=${assembler_linkEditParms},CALL,AMODE(31),RMODE(24) :: **/A31R24/*.asm
assembler_linkEditParms=${assembler_linkEditParms},CALL,AMODE(31),RMODE(ANY) :: **/A31RANY/*.asm
assembler_linkEditParms=${assembler_linkEditParms},CALL,AMODE(64),RMODE(ANY) :: **/A64RANY/*.asm
#
assembler_linkEditParms=${assembler_linkEditParms},NCAL,AMODE(31),RMODE(ANY) :: **/r60090.asm,**/t58020.asm,**/u48739.asm
assembler_linkEditParms=${assembler_linkEditParms},NCAL,AMODE(64),RMODE(ANY) :: **/p49644.asm,**/p49646.asm,**/x64412.asm,**/x64422.asm

#
# Hogan specific parms
#

# --- specific PEM ASU modules MUST come before wildcard mappings ---
assembler_BATCHPEM_linkEditParms=XREF,LET,LIST,REUS,CALL,AMODE(31),RMODE(ANY) \
  :: **/pem2cob.asu,**/P49153.asu

assembler_CICSPEM_linkEditParms=XREF,LET,LIST,REUS,CALL,AMODE(31),RMODE(ANY) \
  :: **/pem2cee.asu,**/pem2cod.asu,**/pemcostd.asu,**/P49153.asu

assembler_batchPem="BATCHPEM"
assembler_BATCHPEM_Parms=SYSPARM(BATCHPEM),RENT
assembler_BATCHPEM_linkEditParms=XREF,LET,LIST,REUS,CALL,AMODE(31),RMODE(ANY) :: **/A31RANY/*.asu
assembler_BATCHPEM_linkEditParms=XREF,LET,LIST,REUS,CALL,AMODE(64),RMODE(ANY) :: **/A64RANY/*.asu
assembler_BATCHPEM_suffix=B

assembler_cicsPem="CICSPEM"
assembler_CICSPEM_Parms=SYSPARM(CICSPEM),RENT
assembler_CICSPEM_linkEditParms=XREF,LET,LIST,REUS,CALL,AMODE(31),RMODE(ANY) :: **/A31RANY/*.asu
assembler_CICSPEM_linkEditParms=XREF,LET,LIST,REUS,CALL,AMODE(64),RMODE(ANY) :: **/A64RANY/*.asu
assembler_CICSPEM_suffix=C

#
# (optional) ASMAOPT dataset defining the assembler option list
# can be overridden by file properties
assembler_asmaOptFile=

#
# Optional linkEditStream defining additional link instructions via SYSIN dd
# cobol_linkEditStream=    INCLUDE SYSLIB(COBJT) \n
assembler_linkEditStream=

#
# execute link edit step
# can be overridden by file properties
assembler_linkEdit=true

#
# default Assembler maximum allowed return codes for each step
# can be overridden by file properties
assembler_maxSQLTranslatorRC=4
assembler_maxCICSTranslatorRC=4
assembler_maxRC=4
assembler_ASUmaxRC=4
assembler_maxIDILANGX_RC=8
assembler_linkEditMaxRC=4

#
# lists of properties which should cause a rebuild after being changed
assembler_impactPropertyList=assembler_pgmParms
assembler_impactPropertyListSQL=assembler_db2precompilerParms
assembler_impactPropertyListCICS=assembler_cicsprecompilerParms

#
# ASM dependencySearch configuration
# searchPaths defined in app-properties file
assembler_dependencySearch=${asmMacroSearch};${asmCopySearch}

#
# store abbrev git hash in ssi field
# available for buildTypes impactBuild, mergeBuild and fullBuild
# can be overridden by file properties
assembler_storeSSI=false

#
# flag to generate IDENTIFY statement during link edit phase
# to create an user data record (IDRU) to "sign" the load module with
# an identify String: <application>/<abbreviatedGitHash>
# to increase traceability
#
# can be overridden by file properties
# default: true
assembler_identifyLoad=false

#
# default deployType
assembler_deployType=LOAD

#
# deployType for build files with isCICS=true
assembler_deployTypeCICS=CICSLOAD

#
# deployType for build files with isDLI=true
assembler_deployTypeDLI=IMSLOAD

#
# scan link edit load module for link dependencies
# can be overridden by file properties
assembler_scanLoadModule=false :: **/p49923.asm, **/t4854500.asm, **/v81190.asm, **/p49045.asm, **/p49097.asm
assembler_scanLoadModule=true
assembler_scanLoadModuleASU=false :: **/p49153.asu
assembler_scanLoadModuleASU=true

#
# additional libraries for assembler SYSLIB concatenation, comma-separated
assembler_assemblySyslibConcatenation=TMNTIBA.LPSSORZZ.MACLIB00,CMNTIBA.LPSSORZZ.MACLIB00,PMNTIBA.LPSSORZZ.MACLIB00,TSYSCIC.LPSSORZZ.MACLIB00.SDFHMAC,PSYSACF.LPSSORZZ.MACLIB00.CICS,SYS1.MACLIB,SYS1.MODGEN,SYS1.SASMMAC1,SYS1.SCEEMAC,SYS1.SHASMAC,SYS2.MACLIB

#
# additional libraries for linkEdit SYSLIB concatenation, comma-separated
assembler_linkEditSyslibConcatenation=TMNTIBA.LPSSORZZ.LODLIB00,CMNTIBA.LPSSORZZ.LODLIB00,PMNTIBA.LPSSORZZ.LODLIB00,TSYSCIC.LPSSORZZ.LODLIB00.SDFHLOAD,PMNTAPL.LOADLIB,SYS1.CSSLIB,SYS1.LINKLIB,SYS1.SCEEBIND,SYS1.SCEELKED,SYS1.SEZATCP,SYS2.IBMDB2.SDSNLOAD
