# Application properties used by zAppBuild/language/Assembler.groovy

#
# default BMS map build rank - used to sort language build file list
# leave empty - overridden by file properties if sorting needed
bms_fileBuildRank=

#
# default BMS maximum RC allowed
# can be overridden by file properties
bms_maxRC=0
bms_compileMaxRC=0
bms_batchPEMmaxRC=0
bms_linkEditmaxRC=0

#
# default BMS parameters
# can be overridden by file properties
bms_copyGenParms=SYSPARM(DSECT),DECK,NOOBJECT
bms_compileParms=
#bms_compileParms=SYSPARM(MAP),DECK,NOOBJECT
bms_linkEditParms=MAP,RENT,COMPAT(PM5)
#bms_linkEditParms=XREF,LET,LIST,REUS,CALL


# If using a debug exit for IBM Debug tool, provide the SYSIN instream DD which is appended to SYSIN
# Samp: easytrieve_linkDebugExit=    INCLUDE SYSLIB(EQAD3CXT) \n
#bms_assemblerSYSIN=1 49 303 \n  319  @{member} A 780101 @{member} CICS     050 CICS1 N % \n
bms_assemblerSYSIN_card1=1 49 303
bms_assemblerSYSIN_card2=#319¬¬@{member}¬A¬780101¬@{member}¬CICS¬¬¬¬¬050¬CICS1¬N¬%

#
# lists of properties which should cause a rebuild after being changed
bms_impactPropertyList=bms_copyGenParms,bms_compileParms,bms_linkEditParms

#
# store abbrev git hash in ssi field
# available for buildTypes impactBuild, mergeBuild and fullBuild
# can be overridden by file properties
bms_storeSSI=true

#
# default deployType
bms_deployType=MAPLOAD

#
# default deployType for generated copybooks
bms_copy_deployType=MAPCOPY

#
# BMS dependencySearch configuration
# searchPaths defined in app-properties file
bms_dependencySearch=${asmMacroSearch};${asmCopySearch}

bms_dependenciesDatasetMapping=
#
# additional libraries for assembler SYSLIB concatenation, comma-separated
bms_assemblySyslibConcatenation=TMNTIBA.LPSSORZZ.MACLIB00,CMNTIBA.LPSSORZZ.MACLIB00,PMNTIBA.LPSSORZZ.MACLIB00,TSYSCIC.LPSSORZZ.MACLIB00.SDFHMAC,PSYSACF.LPSSORZZ.MACLIB00.CICS,SYS1.MACLIB,SYS1.MODGEN,SYS1.SCEEMAC,SYS1.SHASMAC,SYS2.MACLIB


#
# additional libraries for linkEdit SYSLIB concatenation, comma-separated
bms_linkEditSyslibConcatenation=TMNTIBA.LPSSORZZ.LODLIB00,CMNTIBA.LPSSORZZ.LODLIB00,PMNTIBA.LPSSORZZ.LODLIB00,PMNTIBA.LPSSORZZ.LODLIB00.PARSERS,TSYSCIC.LPSSORZZ.LODLIB00.SDFHLOAD,PMNTAPL.LOADLIB,SYS1.CSSLIB,SYS1.SCEEBIND,SYS1.SEZATCP,SYS2.IBMDB2.SDSNLOAD,SYS2.IBMZCONN.SBAQLIB1

#
bms_batchPem=BATCHPEM
bms_cicsPem=CICSPEM
#
