isCICS = true :: \
**/cob2zcee.cbl, \
**/u88835.cbl, \
**/x64022.cbl, \
**/x64028.cbl, \
**/x59750.cbl, \
**/x53750.cbl, \
**/xidsweb1.cbl, \
**/pemsetup.cbl, \
**/x49pbs.cbl, \
**/xmsinpt1.cbl, \
**/CIS2MQ02.cbl, \
**/dvm2eph1.cbl, \
**/p49184.cbl, \
**/xcisrcc3.cbl, \
**/p49750.cbl, \
**/idsxweb1.cbl, \
**/atmdesc1.cbl, \
**/u88836.cbl, \
**/p49913c.cbl, \
**/v81900.cbl, \
**/cis2mq01.cbl, \
**/xcisrcc1.cbl, \
**/p49984c.cbl, \
**/p49914.cbl, \
**/idsmqclr.cbl, \
**/p49084c.cbl, \
**/x49pbsst.cbl, \
**/wdetdes1.cbl, \
**/xcisrcc2.cbl, \
**/p49750jr.cbl, \
**/p49001.asu, \
**/p49002.asu, \
**/p49003.asu, \
**/p49004.asu, \
**/p49005.asu, \
**/p49008.asu, \
**/p49009.asu, \
**/p49010.asu, \
**/p49011.asu, \
**/p49013.asu, \
**/p49014.asu, \
**/p49015.asu, \
**/p49018.asu, \
**/p49022.asu, \
**/p49023.asu, \
**/p49024.asu, \
**/p49026.asu, \
**/p49028.asu, \
**/p49029.asu, \
**/p49030.asu, \
**/p49031.asu, \
**/p49032.asu, \
**/p49033.asu, \
**/p49037.asu, \
**/p49039.asu, \
**/p49042.asu, \
**/p49043.asu, \
**/p49046.asu, \
**/p49048.asu, \
**/p49051.asu, \
**/p49052.asu, \
**/p49053.asu, \
**/p49054.asu, \
**/p49055.asu, \
**/p49057.asu, \
**/p49060.asu, \
**/p49061.asu, \
**/p49063.asu, \
**/p49064.asu, \
**/p49065.asu, \
**/p49068.asu, \
**/p49074.asu, \
**/p49075.asu, \
**/p49077.asu, \
**/p49078.asu, \
**/p49080.asu, \
**/p49087.asu, \
**/p49088.asu, \
**/p49091.asu, \
**/p49098.asu, \
**/p49106.asu, \
**/p49153.asu, \
**/p49501.asu, \
**/p49502.asu, \
**/p49519.asu, \
**/p49528.asu, \
**/p49543.asu, \
**/p49599.asu, \
**/p49870.asu, \
**/p49871.asu, \
**/p49999.asu, \
**/pem2cee.asu, \
**/pem2cob.asu, \
**/pemcostd.asu, \
**/p49984c.cbl, \
**/x64028.cbl, \
**/x49pbs.cbl, \
**/u49426.asm, \
**/x64412.asm, \
**/x64422.asm, \
**/x49pbsst.cbl
