# Application properties used by zAppBuild/language/Cobol.groovy


#
# Need to build epsnbrvl.cbl first during cobol builds
# example: cobol_fileBuildRank = 1 :: **/cobol/epsnbrvl.cbl
cobol_fileBuildRank =  1 :: **/pemsetup.cbl
cobol_fileBuildRank =  2 :: **/w400*.cbl

#
# COBOL dependencySearch configuration
# searchPath defined in application.properties
cobol_dependencySearch=${copybookSearch}

#
# default COBOL compiler version
# default COBOL compiler version
# can be overridden by file properties
cobol_compilerVersion=V6

#
# default COBOL maximum RCs allowed
# can be overridden by file properties
cobol_ChangeControlMaxRC=4
cobol_CICSTranslatorMaxRC=4
cobol_compileMaxRC=4
cobol_linkEditMaxRC=4

# lists of properties which should cause a rebuild after being changed
cobol_impactPropertyList=cobol_compilerVersion,cobol_compileParms
cobol_impactPropertyListCICS=cobol_compileCICSParms
cobol_impactPropertyListSQL=cobol_compileSQLParms

#
# default COBOL compiler parameters
# can be overridden by file properties
cobol_compileCICSParms=
cobol_compileSQLParms=SQL
cobol_compileErrorPrefixParms=ADATA,EX(ADX(ELAXMGUX))
cobol_cicsprecompilerParms=SP :: **/x64028.cbl
cobol_cicsprecompilerParms=SOURCE,NOSEQ,COBOL3,NOOPT,SP  :: **/w400*.cbl,**/x49pbs.cbl,**/x49pbsst.cbl
cobol_cicsprecompilerParms=SOURCE

#
# default COBOL compiler parameters
# can be overridden by file properties
#cobol_compileParms=ADATA,RENT,TRUNC(BIN),NUMPROC(MIG),TERM,NUM,LIST,X,ARCH(13),OPT(1) :: **/w400*.cbl,**/x49pbs.cbl,**/x49pbsst.cbl
cobol_compileParms=TEST,ADATA,RENT,TRUNC(BIN),NUMPROC(MIG),TERM,NUM,LIST,X,ARCH(13) :: **/w400*.cbl,**/x49pbs.cbl,**/x49pbsst.cbl
#cobol_compileParms=ADATA,TRUNC(BIN),TERM,NUM,LIST,ARCH(13),OPT(1)
cobol_compileParms=TEST,ADATA,TRUNC(BIN),TERM,NUM,LIST,ARCH(13)


# Compile Options for IBM Debugger. Assuming to keep Dwarf Files inside the load.
# If you would like to separate debug info, additional allocations needed (See COBOL + Debugger libraries)
#cobol_compileDebugParms=TEST
cobol_compileDebugParms=TEST,ADATA

#
# default LinkEdit parameters
# can be overridden by file properties
cobol_linkEditParms=LIST,MAP,XREF,CALL
cobol_linkEditRent=RENT,REUS

cobol_linkEditParms=REUS=RENT,AMODE=31,RMODE=ANY,LIST,MAP,XREF,CALL :: **/w400*.cbl
cobol_linkEditParms=REUS=RENT,AMODE=31,RMODE=ANY,LIST,MAP,XREF,CALL,ALIASES=ALL :: **/x49pbs.cbl,**/x49pbsst.cbl
cobol_linkEditParms=${cobol_linkEditParms},${cobol_linkEditRent},AMODE(31),RMODE(ANY) :: **/A31RANY/*.cbl
cobol_linkEditParms=${cobol_linkEditParms},${cobol_linkEditRent},AMODE(31),RMODE(24) :: **/A31R24/*.cbl
cobol_linkEditParms=${cobol_linkEditParms},AMODE(64),RMODE(ANY) :: **/A64RANY/*.cbl

# Optional linkEditStream defining additional link instructions via SYSIN dd
# cobol_linkEditStream=    INCLUDE SYSLIB(COBJT) \n
cobol_linkEditStream=
cobol_linkEditStream=INCLUDE SYSLIB(DFHXCSTB) :: **/x49pbs.cbl,**/x49pbsst.cbl
cobol_linkEditStream=ORDER DFHELII \n ORDER P49984C \n ORDER CEEUOPT \n INCLUDE SYSLIB(DFHELII) \n INCLUDE SYSLIB(CEEUOPT) \n INCLUDE SYSLIB(CEESG003) \n NAME P49984C(R) \n :: **/p49984c.cbl
cobol_linkEditStream=ORDER P49982B \n ORDER CEEUOPT \n INCLUDE SYSLIB(CEEUOPT) \n INCLUDE SYSLIB(CEESG003) \n NAME P49982B(R) \n :: **/p49982b.cbl

# If using a debug exit for IBM Debug tool, provide the SYSIN instream DD which is appended to SYSIN
# Samp: cobol_linkDebugExit=    INCLUDE SYSLIB(EQAD3CXT) \n
cobol_linkDebugExit=

#
# execute link edit step
# can be overridden by file properties
cobol_linkEdit=true

#
# store abbrev git hash in ssi field
# available for buildTypes impactBuild, mergeBuild and fullBuild
# can be overridden by file properties
cobol_storeSSI=true

#
# flag to generate IDENTIFY statement during link edit phase
# to create an user data record (IDRU) to "sign" the load module with
# an identify String: <application>/<abbreviatedGitHash>
# to increase traceability
#
# can be overridden by file properties
# default: true
# cobol_identifyLoad=true
# Turn off IDENTIFY binder control card statement for generated zunit test cases & p49982b.cbl, p49984c.cbl, x49pbs.cbl which have link cards overrides
cobol_identifyLoad=false::**/p49982b.cbl,**/p49984c.cbl,**/x49pbs.cbl,**/x49pbsst.cbl


#
# default deployType
cobol_deployType=LOAD

#
# deployType for build files with isCICS=true
cobol_deployTypeCICS=CICSLOAD

#
# deployType for build files with isDLI=true
cobol_deployTypeDLI=IMSLOAD

#
# scan link edit load module for link dependencies
# can be overridden by file properties
cobol_scanLoadModule=true

#
# additional libraries for compile SYSLIB concatenation, comma-separated
#cobol_compileSyslibConcatenation=SYS2.IBMZCONN.SBAQCOB -- B50800
cobol_compileSyslibConcatenation=TMNTIBA.LPSSORZZ.CPYLIB00,CMNTIBA.LPSSORZZ.CPYLIB00,PMNTIBA.LPSSORZZ.CPYLIB00,TSYSCIC.LPSSORZZ.CPYLIB00.SDFHCOB,SYS2.IBMZCONN.SBAQCOB
#TSYSIDZ.LPSSORZZ.JOBLIB00.SBZUSAMP

#
# additional libraries for linkEdit SYSLIB concatenation, comma-separated
cobol_linkEditSyslibConcatenation=TMNTIBA.LPSSORZZ.LODLIB00,CMNTIBA.LPSSORZZ.LODLIB00,PMNTIBA.LPSSORZZ.LODLIB00,TMNTIBA.LPSSORZZ.LODLIB00.PARSERS,CMNTIBA.LPSSORZZ.LODLIB00.PARSERS,PMNTIBA.LPSSORZZ.LODLIB00.PARSERS,TSYSCIC.LPSSORZZ.LODLIB00.SDFHEXCI,TSYSCIC.LPSSORZZ.LODLIB00.SDFHLOAD,PMNTAPL.LOADLIB,SYS1.SCEELKED,SYS1.SEZATCP

# adding option for change control validation
#cobol_changeCDMF=false
cobol_changeCDMF=true
cobol_changeCDMF=false :: **/j0000007.cbl,**/t50798.cbl,**/u48679.cbl,**/u53556.cbl,**/x50071z.cbl,**/x51850.cbl,**/x63012.cbl,**/x65028.cbl,**/x65029.cbl,**/xidsweb1.cbl,**/xmsinpt1.cbl

