# Application script mappings and file property overrides

# Script mappings for all application programs
dbb.scriptMapping = Assembler.groovy :: **/*.asm
dbb.scriptMapping = AsmUtil.groovy :: **/*.asu
dbb.scriptMapping = BMS.groovy :: **/*.bms
dbb.scriptMapping = BMSUtil.groovy :: **/*.bmu
dbb.scriptMapping = MFS.groovy :: **/*.mfs
dbb.scriptMapping = PSBgen.groovy :: **/psb/*.asm
dbb.scriptMapping = DBDgen.groovy :: **/dbd/*.asm
dbb.scriptMapping = Cobol.groovy :: **/*.cbl
dbb.scriptMapping = LinkEdit.groovy :: **/*.lnk
dbb.scriptMapping = PLI.groovy :: **/*.pli
dbb.scriptMapping = Easytrieve.groovy :: **/*.ezt
dbb.scriptMapping = TazUnitTest.groovy :: **/*.bzucfg
dbb.scriptMapping = Transfer.groovy :: **/ctl/*.ctl,**/docutext/*.txt,**/job/*.jcl,**/procs/*.jcl,**/other/*.dat, **/*.xml
dbb.scriptMapping = zCEE3.groovy :: **/openapi.yaml
dbb.scriptMapping = CRB.groovy :: **/crb/*.yaml

dbb.scriptMapping = zCEE2.groovy :: **/zosconnect_artefacts/apis/*.*,**/zosconnect_artefacts/services/*.*,**/zosconnect_artefacts/apiRequester/*.properties,**/zosconnect_artefacts/SAR/*.properties

# Default mappings (always present based on DependencyScannerRegistry)
dbb.scannerMapping = "scannerClass":"DependencyScanner", "languageHint":"COB" :: cbl,cpy,cob
dbb.scannerMapping = "scannerClass":"DependencyScanner", "languageHint":"C" :: c, h
dbb.scannerMapping = "scannerClass":"DependencyScanner", "languageHint":"ASM" :: asm, mac, asu
#dbb.scannerMapping = "scannerClass":"DependencyScanner", "languageHint":"ASU" :: asu, asm, mac

dbb.scannerMapping = "scannerClass":"DependencyScanner", "languageHint":"BMS" :: bms, bmu
dbb.scannerMapping = "scannerClass":"DependencyScanner", "languageHint":"EASY" :: ezt, eztm
dbb.scannerMapping = "scannerClass":"DependencyScanner", "languageHint":"CPP" :: cpp, hpp
dbb.scannerMapping = "scannerClass":"DependencyScanner", "languageHint":"PLI" :: pli, inc
# dbb.scannerMapping = "scannerClass":"ZUnitConfigScanner" :: bzucfg
# Custom mappings
dbb.scannerMapping = "scannerClass":"DependencyScanner", "languageHint":"REXX" :: rexx

#
dbb.DependencyScanner.languageHint=ASM :: **/*.asm, **/*.mac,**/*.asu
dbb.DependencyScanner.languageHint=BMS :: **/*.bms,**/*.bmu
dbb.DependencyScanner.languageHint=EASY :: **/*.ezt, **/*.eztm

#
# epsmlist needs to compile as CICS but does not have EXEC CICS statements
# so is not automatically flagged as CICS by dependency scanner
# example: isCICS = true :: **/cobol/epsmlist.cbl, **/link/epsmlist.lnk, **/cobol/epscsmrt.cbl
#### comment out moved to cics_list.properties ##### isCICS = true :: **/p49984c.cbl,**/x64028.cbl,**/x49pbs.cbl,**/u49426.asm,**/x64412.asm,**/x64422.asm,**/x49pbsst.cbl
#isSQL = false
#isMQ = false
#isIMS = false
isHoganMQ = false

#
# epsmlist needs to compile as CICS but does not have EXEC CICS statements
# so is not automatically flagged as CICS by dependency scanner


# Property File Management
#
# Flag to enable the zAppBuild capability to load individual artifact properties files for source files.
# Please see the detailed documentation on file property management at:
# https://github.com/IBM/dbb-zappbuild/docs/FilePropertyManagement.md
# Example 1: Enable individual artifact properties file for all COBOL files: loadFileLevelProperties=true :: **/cobol/*.cbl
# Example 2: The following file path pattern looks for an individual artifact properties file for epsmlist.cbl:
# loadFileLevelProperties = true :: **/cobol/epsmlist.cbl
loadFileLevelProperties = true

#
# Language Configuration properties Management
#
# Flag to enable the zAppBuild capability to load language configuration properties files for source files.
# Please see the detailed documentation on file property management at:
# https://github.com/IBM/dbb-zappbuild/docs/FilePropertyManagement.md
# Example 1: Enable language configuration mapping for all COBOL files: loadLanguageConfigurationProperties=true :: **/cobol/*.cbl
# Example 2: The following file path pattern looks for a language configuration properties file mapping for epsnbrvl.cbl and epsmpmt.cbl
# in the application-conf/languageconfigurationMapping.properties file:
# loadLanguageConfigurationProperties = true :: **/cobol/epsnbrvl.cbl, **/cobol/epsmpmt.cbl
loadLanguageConfigurationProperties = true


#########
# TAZ Unit Test Integration
#########
#
# file mapping for generated zUnit Test case programs (Cobol) to use a seperate set of libraries
cobol_testcase = true :: **/tests/*.cbl

# file mapping for generated zUnit Test case programs (PL/I) to use a seperate set of libraries
# pli_testcase = true :: **/tests/*.pli

cobol_storeSSI=false :: **/p49982b.cbl,**/p49984c.cbl,**/x49pbs.cbl,**/x49pbsst.cbl

# skip creating IDENTIFY binder control card statement for generated zunit test cases & p49982b.cbl, p49984c.cbl, x49pbs.cbl which have link cards overrides
# cobol_identifyLoad = false :: **/tests/*.cbl,**/tests/*.pli,**/p49982b.cbl,**/p49984c.cbl,**/x49pbs.cbl,**/x49pbsst.cbl
cobol_identifyLoad = false :: **/tests/*.cbl,**/tests/*.pli

# mapping for overwriting the impactResolution rules in application.properties
impactResolutionRules=[${copybookRule},${linkRule}] :: **/copy/*.cpy,**/cobol/*.cbl,**/tests/*.cbl

#########
# Configuration for Transfer.groovy which copies files to target datasets and report them
# in the BuildReport
#########
#
# PropertyMapping to map files using the Transfer.groovy language script to different target datasets
#
# transfer_datasetMapping = transfer_jclPDS :: **/*.jcl
# transfer_datasetMapping = transfer_xmlPDS :: **/xml/*.*
#
# file mapping for overwriting the default deployType of the Transfer.groovy language script
#
# transfer_deployType = JCL :: **/*.jcl
# transfer_deployType = XML :: **/xml/*.*

#
# Override of the default copy mode to transfer the file to the target library
# Available modes are ASA_TEXT, BINARY, LOAD, and TEXT
# Documentation: https://www.ibm.com/docs/api/v1/content/SS6T76_2.0.0/javadoc/com/ibm/dbb/build/DBBConstants.CopyMode.html
# transfer_copyMode=BINARY :: **/*.object

#########
# Configuration for Transfer.groovy which copies files to target datasets and report them
# in the BuildReport
#########
#
# PropertyMapping to map files using the Transfer.groovy language script to different target datasets
#
#transfer_datasetMapping = transfer_ctlPDS :: **/ctl/*.ctl
#transfer_datasetMapping = transfer_docPDS :: **/docutext/*.txt
#transfer_datasetMapping = transfer_jclPDS :: **/job/*.jcl
#transfer_datasetMapping = transfer_prclPDS :: **/procs/*.jcl
#transfer_datasetMapping = transfer_otherPDS :: **/other/*.dat

#
# file mapping for overwriting the default deployType of the Transfer.groovy language script
#
#transfer_deployType = JCL :: **/job/*.jcl
#transfer_deployType = JCL :: **/procs/*.jcl
#transfer_deployType = TEXT ::  **/docutext/*.txt
#transfer_deployType = TEXT ::  **/ctl/*.ctl

#
# Override of the default copy mode to transfer the file to the target library
# Available modes are ASA_TEXT, BINARY, LOAD, and TEXT
# Documentation: https://www.ibm.com/docs/api/v1/content/SS6T76_2.0.0/javadoc/com/ibm/dbb/build/DBBConstants.CopyMode.html
# transfer_copyMode=BINARY :: **/*.object
#transfer_copyMode=TEXT :: **/job/*.jcl
#transfer_copyMode=TEXT ::  **/procs/*.jcl
#transfer_copyMode=TEXT :: **/docutext/*.txt
#transfer_copyMode=TEXT :: **/ctl/*.ctl


#########
# Configuration for zCEE2.groovy to specify file-level overrides
#########

#
# Mapping of input files with types of files
# PROJECT can be used for SAR and AAR projects
# SAR and ARA can be used for SAR Properties files and ARA properties files
#
# zcee2_inputType=PROJECT :: **/zosconnect_artefacts/apis/**/*.*, **/zosconnect_artefacts/services/**/*.*
# zcee2_inputType=SAR :: **/zosconnect_artefacts/SAR/*.properties
# zcee2_inputType=ARA :: **/zosconnect_artefacts/requester/**/*.properties

#
# Build Rank for zCEE2 artifacts
#
#zcee2_fileBuildRank=1 :: **/zosconnect_artefacts/services/**
#zcee2_fileBuildRank=2 :: **/zosconnect_artefacts/requester/**/*.properties


# CDMF definitions
hogan_ChangeControlPDS=TMNTIBA.LPSSORZZ.CTLLIB00
hogan_ChangeControlMember=IBAPEMVL
#
# MD-2143 - Changes
# Updating CDMF1,2,3 and APSGEN variables to point to H09 files. 
# This will make sure IDz User builds are running against H09 files.
hogan_CDMF1=TMNTIBA.CVSNORZZ.A00.CDMF1
hogan_CDMF2=TMNTIBA.CVSNORZZ.A00.CDMF2
hogan_CDMF3=TMNTIBA.CVSNORZZ.A00.CDMF3
hogan_APSGEN=TMNTIBA.CVSNORZZ.A00.SPSGEN
hogan_CDMFLOAD=TMNTIBA.LPSSORZZ.LODLIB00.H09,TMNTIBA.LPSSORZZ.LODLIB00,CMNTIBA.LPSSORZZ.LODLIB00,PMNTIBA.LPSSORZZ.LODLIB00
#
hogan_batchPem=BATCHPEM
hogan_cicsPem=CICSPEM
