# Application properties used by zAppBuild/language/Assembler.groovy

#
# default Assemble program build rank - used to sort language build file list
# leave empty - overridden by file properties if sorting needed
# example: assembler_fileBuildRank = 1 :: **/assembler/*.asm
# example: assembler_fileBuildRank = 2 :: **/pgm1.asm,**/pgm2.asm
#assembler_fileBuildRank = 10
#assembler_fileBuildRank = 20
#assembler_fileBuildRank = 30
#assembler_fileBuildRank = 40
#assembler_fileBuildRank = 50
#assembler_fileBuildRank = 60
#assembler_fileBuildRank = 70
#assembler_fileBuildRank = 71
#assembler_fileBuildRank = 72
#assembler_fileBuildRank = 73
#assembler_fileBuildRank = 100
assembler_fileBuildRank = 1 ::  **/SB10/*.asm
assembler_fileBuildRank = 2 ::  **/SC10/*.asm


#
# default Assembler parameters
# can be overridden by file properties
#assembler_pgmParms=NODECK,OBJECT,TERM,RENT

#  Default
assembler_pgmParms=NODECK,OBJECT,ASA
#
#  SC10 Compile option
assembler_pgmParms=${assembler_pgmParms} :: **/SC10/*.asm
#
#  SB10 Compile option
assembler_pgmParms=${assembler_pgmParms} :: **/SB10/*.asm
#

assembler_debugParms=
assembler_compileErrorPrefixParms=ADATA,EX(ADX(ELAXHASM))
assembler_eqalangxParms=(ASM ERROR LOUD
assembler_db2precompilerParms=HOST(ASM)
assembler_cicsprecompilerParms=CICS,NOEPILOG,NOPROLOG,SP,GDS
assembler_linkEditParms=LIST,MAP,XREF,LET,NCAL,AMODE(31),RMODE(ANY)
assembler_linkEditRent=NORENT
#
#
#
# (optional) ASMAOPT dataset defining the assembler option list
# can be overridden by file properties
assembler_asmaOptFile=

# Optional linkEditStream defining additional link instructions via SYSIN dd
# cobol_linkEditStream=    INCLUDE SYSLIB(COBJT) \n
assembler_linkEditStream=

#
# execute link edit step
# can be overridden by file properties
assembler_linkEdit=true

#
# default Assembler maximum allowed return codes for each step
# can be overridden by file properties
assembler_maxSQLTranslatorRC=4
assembler_maxCICSTranslatorRC=4
assembler_maxRC=4
assembler_ASUmaxRC=4
#assembler_ASUmaxRC=7
assembler_maxIDILANGX_RC=8
assembler_linkEditMaxRC=4

#
# lists of properties which should cause a rebuild after being changed
assembler_impactPropertyList=assembler_pgmParms
assembler_impactPropertyListSQL=assembler_db2precompilerParms
assembler_impactPropertyListCICS=assembler_cicsprecompilerParms

#
# ASM dependencySearch configuration
# searchPaths defined in app-properties file
assembler_dependencySearch=${asmMacroSearch};${asmCopySearch}

#
# store abbrev git hash in ssi field
# available for buildTypes impactBuild, mergeBuild and fullBuild
# can be overridden by file properties
assembler_storeSSI=false
#assembler_storeSSI=true

#
# flag to generate IDENTIFY statement during link edit phase
# to create an user data record (IDRU) to "sign" the load module with
# an identify String: <application>/<abbreviatedGitHash>
# to increase traceability
#
# can be overridden by file properties
# default: true
assembler_identifyLoad=false
#assembler_identifyLoad=true

#
# default deployType
assembler_deployType=LOAD

#
# deployType for build files with isCICS=true
assembler_deployTypeCICS=CICSLOAD

#
# deployType for build files with isDLI=true
assembler_deployTypeDLI=IMSLOAD

#
# scan link edit load module for link dependencies
# can be overridden by file properties.
#assembler_scanLoadModule=false :: **/pgm1.asm, **/pgm2.asm
assembler_scanLoadModule=true
#
# additional libraries for assembler SYSLIB concatenation, comma-separated
assembler_assemblySyslibConcatenation=TMNTORG.LPSSORZZ.MACLIB00,CMNTORG.LPSSORZZ.MACLIB00,PMNTORG.LPSSORZZ.MACLIB00,TSYSCIC.LPSSORZZ.MACLIB00.SDFHMAC,PSYSACF.LPSSORZZ.MACLIB00.CICS,SYS1.MACLIB,SYS1.MODGEN,SYS1.SASMMAC1,SYS1.SCEEMAC,SYS1.SHASMAC,SYS2.MACLIB
#
# additional libraries for linkEdit SYSLIB concatenation, comma-separated
assembler_linkEditSyslibConcatenation=TMNTORG.LPSSORZZ.LODLIB00,CMNTORG.LPSSORZZ.LODLIB00,PMNTORG.LPSSORZZ.LODLIB00,TSYSCIC.LPSSORZZ.LODLIB00.SDFHLOAD,PMNTAPL.LOADLIB,SYS1.CSSLIB,SYS1.LINKLIB,SYS1.SCEEBIND,SYS1.SCEELKED,SYS1.SEZATCP,SYS2.IBMDB2.SDSNLOAD
