# Application properties used by zAppBuild/language/Cobol.groovy

#
# Need to build epsnbrvl.cbl first during cobol builds
# example: cobol_fileBuildRank = 1 :: **/cobol/epsnbrvl.cbl
#cobol_fileBuildRank =  1 :: **/pgm20.cbl
#cobol_fileBuildRank =  2 :: **/pgm1*.cbl
cobol_fileBuildRank =  1 :: **/SB0A/*.cbl
cobol_fileBuildRank =  2 :: **/SB1A/*.cbl,**/SB1A/*/*.cbl
cobol_fileBuildRank =  3 :: **/MB2A/*.cbl,**/MB2A/*/*.cbl
cobol_fileBuildRank =  4 :: **/MC2A/*/*.cbl
cobol_fileBuildRank =  5 :: **/MC2D/*.cbl
#
# COBOL dependencySearch configuration
# searchPath defined in application.properties
cobol_dependencySearch=${copybookSearch}

# default COBOL compiler version
# can be overridden by file properties
cobol_compilerVersion=V6


#
# default COBOL maximum RCs allowed
# can be overridden by file properties
cobol_CICSTranslatorMaxRC=4
cobol_compileMaxRC=4
cobol_linkEditMaxRC=4
#
#
# lists of properties which should cause a rebuild after being changed
cobol_impactPropertyList=cobol_compilerVersion,cobol_compileParms
cobol_impactPropertyListCICS=cobol_compileCICSParms
cobol_impactPropertyListSQL=cobol_compileSQLParms

#To use the Integrated CICS COBOL compiler the following needs to be set to 'false'
#To use native or stand alone CICS translator set it to 'true'
cobol_useCICSnativeTranslator=false

#
# default COBOL compiler parameters
# can be overridden by file properties
cobol_compileCICSParms=
cobol_compileSQLParms=SQL
cobol_compileErrorPrefixParms=ADATA,EX(ADX(ELAXMGUX))
#
# default COBOL compiler parameters
# can be overridden by file properties
#
cobol_compileParms=TRUNC(BIN),OFFSET,INVDATA
cobol_compileParms=${cobol_compileParms},DYN,ARCH(13),OPT(1) :: **/MB2A/*.cbl,**/MB2A/*/*.cbl
cobol_compileParms=${cobol_compileParms},ARCH(12),OPT(2) :: **/MC2D/*.cbl,**/MC2A/*/*.cbl
cobol_compileParms=${cobol_compileParms},ARCH(12) :: **/SB0A/*.cbl,**/SB1A/*.cbl,**/SB1A/*/*.cbl
#
#
#

#  CICS Parms (CICS integrated compiler is being used)
cobol_compileCICSParms=CICS('SP') :: **/MC2D/*.cbl,**/MC2A/*/*.cbl

#Default: ADATA,TRUNC(BIN),TERM,NUM,LIST,ARCH(13),OPT(1)
#    Sample Batch Cobol options we have: OFF,TRUNC(BIN),AWO,NOZWB,LIST,NOSUPP,NOINLINE

# Compile Options for IBM Debugger. Assuming to keep Dwarf Files inside the load.
# If you would like to separate debug info, additional allocations needed (See COBOL + Debugger libraries)
cobol_compileDebugParms=TEST,ADATA
#
# default LinkEdit parameters
# can be overridden by file properties
cobol_linkEditParms=LIST,MAP,XREF,AMODE(31),RMODE(ANY)

# Optional linkEditStream defining additional link instructions via SYSIN dd
# cobol_linkEditStream=    INCLUDE SYSLIB(COBJT) \n
cobol_linkEditStream=

cobol_linkEditStream=INCLUDE SYSLIB(DFHELII) :: **/DFHELII/*.cbl,**/MC2D/*.cbl
cobol_linkEditStream=INCLUDE SYSLIB(DFHELII) \n INCLUDE SYSLIB(CSQCSTUB) :: **/CSQCSTUB/*.cbl
cobol_linkEditStream=INCLUDE SYSLIB(DFHELII) \n INCLUDE SYSLIB(EZACICAL) :: **/EZACICAL/*.cbl
cobol_linkEditStream=INCLUDE SYSLIB(DFHELII) \n INCLUDE SYSLIB(QDXDMM10) :: **/QDXDMM10/*.cbl
cobol_linkEditStream=INCLUDE SYSLIB(DFHELII) \n INCLUDE SYSLIB(DFHECI) :: **/DFHECI/*.cbl
cobol_linkEditStream=INCLUDE SYSLIB(JTXCTM10) :: **/JTXCTM10/*.cbl
cobol_linkEditStream=INCLUDE SYSLIB(QABRPM43) :: **/QABRPM43/*.cbl
cobol_linkEditStream=INCLUDE SYSLIB(QDXDMM10) \n INCLUDE SYSLIB(QDBDMM10) \n INCLUDE SYSLIB(QDBDMM20) :: **/QDBDMM20/*.cbl
cobol_linkEditStream=INCLUDE SYSLIB(XBBRPM43) :: **/XBBRPM43/*.cbl

# If using a debug exit for IBM Debug tool, provide the SYSIN instream DD which is appended to SYSIN
# Samp: cobol_linkDebugExit=    INCLUDE SYSLIB(EQAD3CXT) \n
cobol_linkDebugExit=

#
# execute link edit step
# can be overridden by file properties
cobol_linkEdit=true

#
# store abbrev git hash in ssi field
# available for buildTypes impactBuild, mergeBuild and fullBuild
# can be overridden by file properties
cobol_storeSSI=true

#
# flag to generate IDENTIFY statement during link edit phase
# to create an user data record (IDRU) to "sign" the load module with
# an identify String: <application>/<abbreviatedGitHash>
# to increase traceability
#
# can be overridden by file properties
# default: true
# cobol_identifyLoad=true
# Turn off IDENTIFY binder control card statement for generated zunit test cases & p49982b.cbl, p49984c.cbl, x49pbs.cbl which have link cards overrides
#cobol_identifyLoad=false::**/pgm1.cbl,**/pgm2*.cbl


#
#
# default deployType
cobol_deployType=LOAD

#
# deployType for build files with isCICS=true
cobol_deployTypeCICS=CICSLOAD

#
# deployType for build files with isDLI=true
cobol_deployTypeDLI=IMSLOAD

#
# scan link edit load module for link dependencies
# can be overridden by file properties
cobol_scanLoadModule=true

#
#
## additional libraries for compile SYSLIB concatenation, comma-separated
cobol_compileSyslibConcatenation=TMNTORG.LPSSORZZ.CPYLIB00,CMNTORG.LPSSORZZ.CPYLIB00,PMNTORG.LPSSORZZ.CPYLIB00,TMNTILN.LPSSORZZ.CPYLIB00,CMNTILN.LPSSORZZ.CPYLIB00,PMNTILN.LPSSORZZ.CPYLIB00,TMNTIBA.LPSSORZZ.CPYLIB00,CMNTIBA.LPSSORZZ.CPYLIB00,PMNTIBA.LPSSORZZ.CPYLIB00,TSYSCIC.LPSSORZZ.CPYLIB00.SDFHCOB,TSYSMQS.LPSSORZZ.CPYLIB00.SCSQCOBC,SYS2.IBMZCONN.SBAQCOB
#
# additional libraries for linkEdit SYSLIB concatenation, comma-separated
cobol_linkEditSyslibConcatenation=TMNTORG.LPSSORZZ.LODLIB00,CMNTORG.LPSSORZZ.LODLIB00,PMNTORG.LPSSORZZ.LODLIB00,TSYSCIC.LPSSORZZ.LODLIB00.SDFHEXCI,TSYSCIC.LPSSORZZ.LODLIB00.SDFHLOAD,PMNTAPL.LOADLIB,SYS1.SCEELKED,SYS1.SEZATCP,SYS1.SCEECICS,SYS2.IBMMQS.SCSQLOAD
#
# adding option for change control validation
cobol_changeCDMF=false
#cobol_changeCDMF=true

